### ISSUE TITLE
airworthiness

### ISSUE THREAD

**Issue by maldivski** [sobester/ADRpy#27]
I tried to plot the V-n diagram, as showed in the example in ADRpy, but these errors showed up:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from ADRpy import airworthiness as aw
      2 from ADRpy import unitconversions as co
      3 from ADRpy import atmospheres as at

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\adrpy-0.2.5-py3.10.egg\ADRpy\airworthiness.py:20, in <module>
     17 import math
     18 import warnings
---> 20 import numpy as np
     21 from matplotlib import text as mpl_text
     22 from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'numpy'`
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 designatm = at.Atmosphere()

NameError: name 'at' is not defined`
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 concept = aw.CertificationSpecifications(designbrief, designdef, designperf, designatm, designpropulsion, csbrief)

NameError: name 'aw' is not defined`
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 point=concept.flightenvelope(textsize=15, figsize_in=[15, 10], show=True)

NameError: name 'concept' is not defined`

**Comment by sobester** [comment]
Dear maldivski,

Thank you for getting in touch. The error message you are getting - ModuleNotFoundError: No module named 'numpy' - refers to your system missing numpy - installing it should resolve the issue. 

Best wishes
Andras
