### ISSUE TITLE
propulsion __init__ naming in _setup

### ISSUE THREAD

**Issue by bolandess** [sobester/ADRpy#37]
There may be a file naming issue in the propulsion.py file near line 568. Following the online example, I executed the following commands

```
from ADRpy import propulsion as decks
import numpy as np
import matplotlib.pyplot as plt
piston = decks.PistonDeck("IO-540")
```

When calling the `decks.PistonDeck("IO-540")`, I receive the following error

```
Traceback (most recent call last):
  Cell In[54], line 6
    piston = decks.PistonDeck("IO-540")  # Selects data for the IO-540
  File E:\anaconda3\lib\site-packages\ADRpy\propulsion.py:575 in __init__
    spd_pwr = pd.DataFrame.to_numpy(power_df["Speed (RPM)"])
  File E:\anaconda3\lib\site-packages\pandas\core\frame.py:1838 in to_numpy
    result = self._mgr.as_array(dtype=dtype, copy=copy, na_value=na_value)
AttributeError: 'SingleBlockManager' object has no attribute 'as_array'
```

I initially thought it was my numpy and pandas version so I updated them to the most current revision available. That did not fix the issue. ADRpy was verified to be version 0.2.5.

I eventually traced the error back to the propulsion.py file where the `__init__` function correctly assembles the folderpath to where the Piston_CSVs are saved, then the next line calls the following

`data, self.data_available = _setup(engine_name, folderpath, ["power"], ["bsfc", "bsfc_best_power"])`

I noticed there were no files named "power", "bsfc", or "bsfc_best_power"; however, there were files that ended in _data. I removed the _data filename extension (i.e., I changed "IO-540_power_data.csv" to "IO-540_power.csv"). The command successfully ran, but then the example code did not produce any plots from the code given in the example notebooks.

I then re-added the _data in the filename, and changed the variables in propulsion.py line 568 to be 

`data, self.data_available = _setup(engine_name, folderpath, ["IO-540_power_data"], ["IO-540_bsfc_data_data", "IO-540_bsfc_best_power_data"])`

which successfully executed, but then the example code would not plot anything due to the `power = piston.shaftpower(engine_speed, alt)` being empty. Here, engine_speed and alt were successfully created with the np.linspace command.

I think the entire problem traces back to the variable naming convention in either the csv files or the _setup function. With all variables and csv filenames back to their original names, the following print command produced the result

```
print(self.data_available)
[[True], [True, True], False, False]
```

Am I using the commands incorrectly or is there a code error and/or naming convention error? I would like to add my own engine models to the Piston_CSVs folder, but I need to get this running properly first.

Thank you for the help.

**Comment by yaseen157** [comment]
Hi bolandess,

Apologies for the late reply, we've been hard at work gutting and re-working ADRpy.
The error you are encountering is because the pandas library is deprecating the conversion from dataframe to array in that manner.

ADRpy version 0.2.6 is on the way in the next few days to address this issue and should be downloadable via PyPI soon. You can look at the pull request I've made to ADRpy (patch 5) to see what's changed.

If you'd instead like to tinker with a more capable version of ADRpy, check out my fork of ADRpy 0.3.0. Feedback is welcome, and will be helpful as I develop ADRpy's bigger, more capable sibling library (release date TBD but probably this year).

**Comment by sobester** [comment]
Patch 5 now merged.
